apiVersion: v1
kind: Service
metadata:
  name: job-portal
  namespace: default
spec:
  selector:
    app: job-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
